import { Injectable, Logger } from "@nestjs/common"
import { BaseService } from "../BaseService"

@Injectable()
export class CountryService extends BaseService {
	private readonly logger = new Logger(CountryService.name)

	public getValidLabels(): string[] {
		return [
			"AF",
			"AL",
			"DZ",
			"AS",
			"AD",
			"AO",
			"AI",
			"AQ",
			"AG",
			"AR",
			"AM",
			"AW",
			"AU",
			"AT",
			"AZ",
			"BS",
			"BH",
			"BD",
			"BB",
			"BY",
			"BE",
			"BZ",
			"BJ",
			"BM",
			"BT",
			"BO",
			"BA",
			"BW",
			"BR",
			"BN",
			"BG",
			"BF",
			"BI",
			"KH",
			"CM",
			"CA",
			"CV",
			"KY",
			"CF",
			"TD",
			"CL",
			"CN",
			"CO",
			"KM",
			"CG",
			"CD",
			"CR",
			"HR",
			"CU",
			"CY",
			"CZ",
			"DK",
			"DJ",
			"DM",
			"DO",
			"EC",
			"EG",
			"SV",
			"GQ",
			"ER",
			"EE",
			"SZ",
			"ET",
			"FJ",
			"FI",
			"FR",
			"GA",
			"GM",
			"GE",
			"DE",
			"GH",
			"GR",
			"GD",
			"GU",
			"GT",
			"GN",
			"GW",
			"GY",
			"HT",
			"HN",
			"HK",
			"HU",
			"IS",
			"IN",
			"ID",
			"IR",
			"IQ",
			"IE",
			"IL",
			"IT",
			"JM",
			"JP",
			"JO",
			"KZ",
			"KE",
			"KI",
			"KP",
			"KR",
			"KW",
			"KG",
			"LA",
			"LV",
			"LB",
			"LS",
			"LR",
			"LY",
			"LI",
			"LT",
			"LU",
			"MO",
			"MK",
			"MG",
			"MW",
			"MY",
			"MV",
			"ML",
			"MT",
			"MH",
			"MR",
			"MU",
			"MX",
			"FM",
			"MD",
			"MC",
			"MN",
			"ME",
			"MA",
			"MZ",
			"MM",
			"NA",
			"NR",
			"NP",
			"NL",
			"NZ",
			"NI",
			"NE",
			"NG",
			"NO",
			"OM",
			"PK",
			"PW",
			"PA",
			"PG",
			"PY",
			"PE",
			"PH",
			"PL",
			"PT",
			"QA",
			"RO",
			"RU",
			"RW",
			"KN",
			"LC",
			"VC",
			"WS",
			"SM",
			"ST",
			"SA",
			"SN",
			"RS",
			"SC",
			"SL",
			"SG",
			"SK",
			"SI",
			"SB",
			"SO",
			"ZA",
			"SS",
			"ES",
			"LK",
			"SD",
			"SR",
			"SE",
			"CH",
			"SY",
			"TW",
			"TJ",
			"TZ",
			"TH",
			"TL",
			"TG",
			"TO",
			"TT",
			"TN",
			"TR",
			"TM",
			"TV",
			"UG",
			"UA",
			"AE",
			"GB",
			"US",
			"UY",
			"UZ",
			"VU",
			"VE",
			"VN",
			"YE",
			"ZM",
			"ZW",
		]
	}

	public getData<T>(): T[] {
		return [
			{ iso: "AF", country: "Afghanistan" },
			{ iso: "AL", country: "Albania" },
			{ iso: "DZ", country: "Algeria" },
			{ iso: "AS", country: "American Samoa" },
			{ iso: "AD", country: "Andorra" },
			{ iso: "AO", country: "Angola" },
			{ iso: "AI", country: "Anguilla" },
			{ iso: "AQ", country: "Antarctica" },
			{ iso: "AG", country: "Antigua and Barbuda" },
			{ iso: "AR", country: "Argentina" },
			{ iso: "AM", country: "Armenia" },
			{ iso: "AW", country: "Aruba" },
			{ iso: "AU", country: "Australia" },
			{ iso: "AT", country: "Austria" },
			{ iso: "AZ", country: "Azerbaijan" },
			{ iso: "BS", country: "Bahamas" },
			{ iso: "BH", country: "Bahrain" },
			{ iso: "BD", country: "Bangladesh" },
			{ iso: "BB", country: "Barbados" },
			{ iso: "BY", country: "Belarus" },
			{ iso: "BE", country: "Belgium" },
			{ iso: "BZ", country: "Belize" },
			{ iso: "BJ", country: "Benin" },
			{ iso: "BM", country: "Bermuda" },
			{ iso: "BT", country: "Bhutan" },
			{ iso: "BO", country: "Bolivia" },
			{ iso: "BA", country: "Bosnia and Herzegovina" },
			{ iso: "BW", country: "Botswana" },
			{ iso: "BR", country: "Brazil" },
			{ iso: "BN", country: "Brunei" },
			{ iso: "BG", country: "Bulgaria" },
			{ iso: "BF", country: "Burkina Faso" },
			{ iso: "BI", country: "Burundi" },
			{ iso: "KH", country: "Cambodia" },
			{ iso: "CM", country: "Cameroon" },
			{ iso: "CA", country: "Canada" },
			{ iso: "CV", country: "Cape Verde" },
			{ iso: "KY", country: "Cayman Islands" },
			{ iso: "CF", country: "Central African Republic" },
			{ iso: "TD", country: "Chad" },
			{ iso: "CL", country: "Chile" },
			{ iso: "CN", country: "China" },
			{ iso: "CO", country: "Colombia" },
			{ iso: "KM", country: "Comoros" },
			{ iso: "CG", country: "Congo" },
			{ iso: "CD", country: "Congo (Democratic Republic)" },
			{ iso: "CR", country: "Costa Rica" },
			{ iso: "HR", country: "Croatia" },
			{ iso: "CU", country: "Cuba" },
			{ iso: "CY", country: "Cyprus" },
			{ iso: "CZ", country: "Czech Republic" },
			{ iso: "DK", country: "Denmark" },
			{ iso: "DJ", country: "Djibouti" },
			{ iso: "DM", country: "Dominica" },
			{ iso: "DO", country: "Dominican Republic" },
			{ iso: "EC", country: "Ecuador" },
			{ iso: "EG", country: "Egypt" },
			{ iso: "SV", country: "El Salvador" },
			{ iso: "GQ", country: "Equatorial Guinea" },
			{ iso: "ER", country: "Eritrea" },
			{ iso: "EE", country: "Estonia" },
			{ iso: "SZ", country: "Eswatini" },
			{ iso: "ET", country: "Ethiopia" },
			{ iso: "FJ", country: "Fiji" },
			{ iso: "FI", country: "Finland" },
			{ iso: "FR", country: "France" },
			{ iso: "GA", country: "Gabon" },
			{ iso: "GM", country: "Gambia" },
			{ iso: "GE", country: "Georgia" },
			{ iso: "DE", country: "Germany" },
			{ iso: "GH", country: "Ghana" },
			{ iso: "GR", country: "Greece" },
			{ iso: "GD", country: "Grenada" },
			{ iso: "GU", country: "Guam" },
			{ iso: "GT", country: "Guatemala" },
			{ iso: "GN", country: "Guinea" },
			{ iso: "GW", country: "Guinea-Bissau" },
			{ iso: "GY", country: "Guyana" },
			{ iso: "HT", country: "Haiti" },
			{ iso: "HN", country: "Honduras" },
			{ iso: "HK", country: "Hong Kong" },
			{ iso: "HU", country: "Hungary" },
			{ iso: "IS", country: "Iceland" },
			{ iso: "IN", country: "India" },
			{ iso: "ID", country: "Indonesia" },
			{ iso: "IR", country: "Iran" },
			{ iso: "IQ", country: "Iraq" },
			{ iso: "IE", country: "Ireland" },
			{ iso: "IL", country: "Israel" },
			{ iso: "IT", country: "Italy" },
			{ iso: "JM", country: "Jamaica" },
			{ iso: "JP", country: "Japan" },
			{ iso: "JO", country: "Jordan" },
			{ iso: "KZ", country: "Kazakhstan" },
			{ iso: "KE", country: "Kenya" },
			{ iso: "KI", country: "Kiribati" },
			{ iso: "KP", country: "North Korea" },
			{ iso: "KR", country: "South Korea" },
			{ iso: "KW", country: "Kuwait" },
			{ iso: "KG", country: "Kyrgyzstan" },
			{ iso: "LA", country: "Laos" },
			{ iso: "LV", country: "Latvia" },
			{ iso: "LB", country: "Lebanon" },
			{ iso: "LS", country: "Lesotho" },
			{ iso: "LR", country: "Liberia" },
			{ iso: "LY", country: "Libya" },
			{ iso: "LI", country: "Liechtenstein" },
			{ iso: "LT", country: "Lithuania" },
			{ iso: "LU", country: "Luxembourg" },
			{ iso: "MO", country: "Macau" },
			{ iso: "MK", country: "North Macedonia" },
			{ iso: "MG", country: "Madagascar" },
			{ iso: "MW", country: "Malawi" },
			{ iso: "MY", country: "Malaysia" },
			{ iso: "MV", country: "Maldives" },
			{ iso: "ML", country: "Mali" },
			{ iso: "MT", country: "Malta" },
			{ iso: "MH", country: "Marshall Islands" },
			{ iso: "MR", country: "Mauritania" },
			{ iso: "MU", country: "Mauritius" },
			{ iso: "MX", country: "Mexico" },
			{ iso: "FM", country: "Micronesia" },
			{ iso: "MD", country: "Moldova" },
			{ iso: "MC", country: "Monaco" },
			{ iso: "MN", country: "Mongolia" },
			{ iso: "ME", country: "Montenegro" },
			{ iso: "MA", country: "Morocco" },
			{ iso: "MZ", country: "Mozambique" },
			{ iso: "MM", country: "Myanmar" },
			{ iso: "NA", country: "Namibia" },
			{ iso: "NR", country: "Nauru" },
			{ iso: "NP", country: "Nepal" },
			{ iso: "NL", country: "Netherlands" },
			{ iso: "NZ", country: "New Zealand" },
			{ iso: "NI", country: "Nicaragua" },
			{ iso: "NE", country: "Niger" },
			{ iso: "NG", country: "Nigeria" },
			{ iso: "NO", country: "Norway" },
			{ iso: "OM", country: "Oman" },
			{ iso: "PK", country: "Pakistan" },
			{ iso: "PW", country: "Palau" },
			{ iso: "PA", country: "Panama" },
			{ iso: "PG", country: "Papua New Guinea" },
			{ iso: "PY", country: "Paraguay" },
			{ iso: "PE", country: "Peru" },
			{ iso: "PH", country: "Philippines" },
			{ iso: "PL", country: "Poland" },
			{ iso: "PT", country: "Portugal" },
			{ iso: "QA", country: "Qatar" },
			{ iso: "RO", country: "Romania" },
			{ iso: "RU", country: "Russia" },
			{ iso: "RW", country: "Rwanda" },
			{ iso: "KN", country: "Saint Kitts and Nevis" },
			{ iso: "LC", country: "Saint Lucia" },
			{ iso: "VC", country: "Saint Vincent and the Grenadines" },
			{ iso: "WS", country: "Samoa" },
			{ iso: "SM", country: "San Marino" },
			{ iso: "ST", country: "Sao Tome and Principe" },
			{ iso: "SA", country: "Saudi Arabia" },
			{ iso: "SN", country: "Senegal" },
			{ iso: "RS", country: "Serbia" },
			{ iso: "SC", country: "Seychelles" },
			{ iso: "SL", country: "Sierra Leone" },
			{ iso: "SG", country: "Singapore" },
			{ iso: "SK", country: "Slovakia" },
			{ iso: "SI", country: "Slovenia" },
			{ iso: "SB", country: "Solomon Islands" },
			{ iso: "SO", country: "Somalia" },
			{ iso: "ZA", country: "South Africa" },
			{ iso: "SS", country: "South Sudan" },
			{ iso: "ES", country: "Spain" },
			{ iso: "LK", country: "Sri Lanka" },
			{ iso: "SD", country: "Sudan" },
			{ iso: "SR", country: "Suriname" },
			{ iso: "SE", country: "Sweden" },
			{ iso: "CH", country: "Switzerland" },
			{ iso: "SY", country: "Syria" },
			{ iso: "TW", country: "Taiwan" },
			{ iso: "TJ", country: "Tajikistan" },
			{ iso: "TZ", country: "Tanzania" },
			{ iso: "TH", country: "Thailand" },
			{ iso: "TL", country: "Timor-Leste" },
			{ iso: "TG", country: "Togo" },
			{ iso: "TO", country: "Tonga" },
			{ iso: "TT", country: "Trinidad and Tobago" },
			{ iso: "TN", country: "Tunisia" },
			{ iso: "TR", country: "Turkey" },
			{ iso: "TM", country: "Turkmenistan" },
			{ iso: "TV", country: "Tuvalu" },
			{ iso: "UG", country: "Uganda" },
			{ iso: "UA", country: "Ukraine" },
			{ iso: "AE", country: "United Arab Emirates" },
			{ iso: "GB", country: "United Kingdom" },
			{ iso: "US", country: "United States" },
			{ iso: "UY", country: "Uruguay" },
			{ iso: "UZ", country: "Uzbekistan" },
			{ iso: "VU", country: "Vanuatu" },
			{ iso: "VE", country: "Venezuela" },
			{ iso: "VN", country: "Vietnam" },
			{ iso: "YE", country: "Yemen" },
			{ iso: "ZM", country: "Zambia" },
			{ iso: "ZW", country: "Zimbabwe " },
		] as T[];
	}
}
